import type { Branch, Moment } from "./types";

export const MOCK_BRANCHES: Branch[] = [
  {
    id: 'branch-work-1',
    userId: 'mock-user',
    limbId: 'work',
    label: 'Marketing career',
    parentBranchId: null,
    turningPointId: null,
    mapAngleOffset: 0,
    createdAt: '2013-09-01'
  },
  {
    id: 'branch-health-1',
    userId: 'mock-user',
    limbId: 'health',
    label: 'Fitness journey',
    parentBranchId: null,
    turningPointId: null,
    mapAngleOffset: 0,
    createdAt: '2014-01-01'
  },
  {
    id: 'branch-people-1',
    userId: 'mock-user',
    limbId: 'people',
    label: 'Relationships',
    parentBranchId: null,
    turningPointId: null,
    mapAngleOffset: 0,
    createdAt: '2013-09-01'
  },
  {
    id: 'branch-finance-1',
    userId: 'mock-user',
    limbId: 'finance',
    label: 'Financial journey',
    parentBranchId: null,
    turningPointId: null,
    mapAngleOffset: 0,
    createdAt: '2013-09-01'
  },
  {
    id: 'branch-becoming-1',
    userId: 'mock-user',
    limbId: 'becoming',
    label: 'Personal growth',
    parentBranchId: null,
    turningPointId: null,
    mapAngleOffset: 0,
    createdAt: '2014-01-01'
  },
]

export const MOCK_MOMENTS: Moment[] = [

  // ── WORK & CAREER ──────────────────────
  // 8 moments — rich career arc with pivot
  {
    id: 'moment-work-1',
    userId: 'mock-user',
    limbId: 'work',
    branchId: 'branch-work-1',
    label: 'First Marketing Job',
    description: 'Junior coordinator at a Manchester agency. Lowest rung but learned fast.',
    year: 2013,
    month: 9,
    mapPosition: 0,
    significance: 2,
    future: false,
    isTurningPoint: false,
    location: 'Manchester, UK',
    timelineNote: null,
    createdAt: '2013-09-01',
    updatedAt: '2013-09-01'
  },
  {
    id: 'moment-work-2',
    userId: 'mock-user',
    limbId: 'work',
    branchId: 'branch-work-1',
    label: 'Moved to London',
    description: 'Took a risk on a bigger agency. Scary but necessary.',
    year: 2015,
    month: 3,
    mapPosition: 1,
    significance: 3,
    future: false,
    isTurningPoint: false,
    location: 'London, UK',
    timelineNote: 'This was the first time I chose discomfort deliberately.',
    createdAt: '2015-03-01',
    updatedAt: '2015-03-01'
  },
  {
    id: 'moment-work-3',
    userId: 'mock-user',
    limbId: 'work',
    branchId: 'branch-work-1',
    label: 'Promoted to Senior',
    description: 'Three years of grinding paid off. Finally felt like I belonged.',
    year: 2017,
    month: 6,
    mapPosition: 2,
    significance: 2,
    future: false,
    isTurningPoint: false,
    location: 'London, UK',
    timelineNote: null,
    createdAt: '2017-06-01',
    updatedAt: '2017-06-01'
  },
  {
    id: 'moment-work-4',
    userId: 'mock-user',
    limbId: 'work',
    branchId: 'branch-work-1',
    label: 'Berlin Sabbatical',
    description: 'Six months freelancing in Berlin. Changed everything about how I work.',
    year: 2019,
    month: 1,
    mapPosition: 3,
    significance: 3,
    future: false,
    isTurningPoint: false,
    location: 'Berlin, Germany',
    timelineNote: 'Realised I had been optimising for the wrong things.',
    createdAt: '2019-01-01',
    updatedAt: '2019-01-01'
  },
  {
    id: 'moment-work-5',
    userId: 'mock-user',
    limbId: 'work',
    branchId: 'branch-work-1',
    label: 'Pivoted to Product',
    description: 'Left marketing entirely. Joined a startup as first product hire.',
    year: 2020,
    month: 9,
    mapPosition: 4,
    significance: 3,
    future: false,
    isTurningPoint: false,
    location: 'London, UK',
    timelineNote: 'The scariest professional decision I have made so far.',
    createdAt: '2020-09-01',
    updatedAt: '2020-09-01'
  },
  {
    id: 'moment-work-6',
    userId: 'mock-user',
    limbId: 'work',
    branchId: 'branch-work-1',
    label: 'Lead PM at Scale-up',
    description: 'Joined a Series B company. Learned what real product pressure feels like.',
    year: 2022,
    month: 3,
    mapPosition: 5,
    significance: 2,
    future: false,
    isTurningPoint: false,
    location: 'London, UK',
    timelineNote: null,
    createdAt: '2022-03-01',
    updatedAt: '2022-03-01'
  },
  {
    id: 'moment-work-7',
    userId: 'mock-user',
    limbId: 'work',
    branchId: 'branch-work-1',
    label: 'Left to Build Own Thing',
    description: 'Quit stable job to build a startup. No safety net.',
    year: 2024,
    month: 1,
    mapPosition: 6,
    significance: 3,
    future: false,
    isTurningPoint: false,
    location: 'London, UK',
    timelineNote: 'The day I stopped renting my ambition to someone else.',
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01'
  },
  {
    id: 'moment-work-8',
    userId: 'mock-user',
    limbId: 'work',
    branchId: 'branch-work-1',
    label: 'First Paying Customer',
    description: 'Someone paid real money for something I built.',
    year: 2026,
    month: 6,
    mapPosition: 7,
    significance: 3,
    future: true,
    isTurningPoint: false,
    location: null,
    timelineNote: null,
    createdAt: '2025-01-01',
    updatedAt: '2025-01-01'
  },

  // ── HEALTH & BODY ──────────────────────
  // 7 moments — struggle, transformation, goals
  {
    id: 'moment-health-1',
    userId: 'mock-user',
    limbId: 'health',
    branchId: 'branch-health-1',
    label: 'Heaviest I Have Been',
    description: '94kg. Desk job, takeaways, no exercise. Woke up one day and hated the mirror.',
    year: 2016,
    month: 2,
    mapPosition: 0,
    significance: 3,
    future: false,
    isTurningPoint: false,
    location: 'London, UK',
    timelineNote: 'This was the bottom. Everything since has been up.',
    createdAt: '2016-02-01',
    updatedAt: '2016-02-01'
  },
  {
    id: 'moment-health-2',
    userId: 'mock-user',
    limbId: 'health',
    branchId: 'branch-health-1',
    label: 'First 5km Run',
    description: 'Could not finish it. Walked half. Did not care — kept going.',
    year: 2016,
    month: 6,
    mapPosition: 1,
    significance: 2,
    future: false,
    isTurningPoint: false,
    location: 'London, UK',
    timelineNote: null,
    createdAt: '2016-06-01',
    updatedAt: '2016-06-01'
  },
  {
    id: 'moment-health-3',
    userId: 'mock-user',
    limbId: 'health',
    branchId: 'branch-health-1',
    label: 'Lost 15kg',
    description: 'Took 18 months. No crash diet — just consistency.',
    year: 2017,
    month: 11,
    mapPosition: 2,
    significance: 3,
    future: false,
    isTurningPoint: false,
    location: null,
    timelineNote: 'Proved to myself I can do hard things slowly.',
    createdAt: '2017-11-01',
    updatedAt: '2017-11-01'
  },
  {
    id: 'moment-health-4',
    userId: 'mock-user',
    limbId: 'health',
    branchId: 'branch-health-1',
    label: 'First Half Marathon',
    description: 'Berlin half marathon. 2 hours 4 minutes. Cried at the finish line.',
    year: 2019,
    month: 9,
    mapPosition: 3,
    significance: 3,
    future: false,
    isTurningPoint: false,
    location: 'Berlin, Germany',
    timelineNote: null,
    createdAt: '2019-09-01',
    updatedAt: '2019-09-01'
  },
  {
    id: 'moment-health-5',
    userId: 'mock-user',
    limbId: 'health',
    branchId: 'branch-health-1',
    label: 'Burnout and Weight Gain',
    description: 'Startup stress undid two years of progress. Back to 86kg.',
    year: 2021,
    month: 4,
    mapPosition: 4,
    significance: 2,
    future: false,
    isTurningPoint: false,
    location: null,
    timelineNote: 'Health is always the first thing I sacrifice. Need to fix this pattern.',
    createdAt: '2021-04-01',
    updatedAt: '2021-04-01'
  },
  {
    id: 'moment-health-6',
    userId: 'mock-user',
    limbId: 'health',
    branchId: 'branch-health-1',
    label: 'Back to Training',
    description: 'Rebuilt the habit from scratch. Smaller goals this time.',
    year: 2023,
    month: 1,
    mapPosition: 5,
    significance: 2,
    future: false,
    isTurningPoint: false,
    location: 'London, UK',
    timelineNote: null,
    createdAt: '2023-01-01',
    updatedAt: '2023-01-01'
  },
  {
    id: 'moment-health-7',
    userId: 'mock-user',
    limbId: 'health',
    branchId: 'branch-health-1',
    label: 'Full Marathon Goal',
    description: 'London Marathon 2026. Training starts now.',
    year: 2026,
    month: 4,
    mapPosition: 6,
    significance: 3,
    future: true,
    isTurningPoint: false,
    location: 'London, UK',
    timelineNote: null,
    createdAt: '2025-01-01',
    updatedAt: '2025-01-01'
  },

  // ── PEOPLE & RELATIONSHIPS ─────────────
  // 7 moments — friends, family, romance
  {
    id: 'moment-people-1',
    userId: 'mock-user',
    limbId: 'people',
    branchId: 'branch-people-1',
    label: 'Left Manchester Friends',
    description: 'Moving to London meant leaving behind everyone I grew up with.',
    year: 2015,
    month: 3,
    mapPosition: 0,
    significance: 2,
    future: false,
    isTurningPoint: false,
    location: 'Manchester, UK',
    subtype: 'friends',
    timelineNote: 'Some friendships survived. Most did not.',
    createdAt: '2015-03-01',
    updatedAt: '2015-03-01'
  },
  {
    id: 'moment-people-2',
    userId: 'mock-user',
    limbId: 'people',
    branchId: 'branch-people-1',
    label: 'Met Jamie',
    description: 'At a work event. We argued about everything and became best friends.',
    year: 2016,
    month: 8,
    mapPosition: 1,
    significance: 3,
    future: false,
    isTurningPoint: false,
    location: 'London, UK',
    subtype: 'friends',
    timelineNote: null,
    createdAt: '2016-08-01',
    updatedAt: '2016-08-01'
  },
  {
    id: 'moment-people-3',
    userId: 'mock-user',
    limbId: 'people',
    branchId: 'branch-people-1',
    label: 'Dad Got Ill',
    description: 'Cancer diagnosis. Everything else stopped mattering for a while.',
    year: 2018,
    month: 5,
    mapPosition: 2,
    significance: 3,
    future: false,
    isTurningPoint: false,
    location: 'Manchester, UK',
    subtype: 'family',
    timelineNote: 'Made me think hard about what I was actually doing with my time.',
    createdAt: '2018-05-01',
    updatedAt: '2018-05-01'
  },
  {
    id: 'moment-people-4',
    userId: 'mock-user',
    limbId: 'people',
    branchId: 'branch-people-1',
    label: 'Met Sam in Berlin',
    description: 'At a co-working space. Did not expect to fall for someone on a sabbatical.',
    year: 2019,
    month: 3,
    mapPosition: 3,
    significance: 3,
    future: false,
    isTurningPoint: false,
    location: 'Berlin, Germany',
    subtype: 'romance',
    timelineNote: null,
    createdAt: '2019-03-01',
    updatedAt: '2019-03-01'
  },
  {
    id: 'moment-people-5',
    userId: 'mock-user',
    limbId: 'people',
    branchId: 'branch-people-1',
    label: 'Dad in Remission',
    description: 'Two years of treatment. He made it.',
    year: 2020,
    month: 6,
    mapPosition: 4,
    significance: 3,
    future: false,
    isTurningPoint: false,
    location: 'Manchester, UK',
    subtype: 'family',
    timelineNote: 'The relief was physical.',
    createdAt: '2020-06-01',
    updatedAt: '2020-06-01'
  },
  {
    id: 'moment-people-6',
    userId: 'mock-user',
    limbId: 'people',
    branchId: 'branch-people-1',
    label: 'Moved in with Sam',
    description: 'Long distance for two years then finally the same city.',
    year: 2021,
    month: 9,
    mapPosition: 5,
    significance: 3,
    future: false,
    isTurningPoint: false,
    location: 'London, UK',
    subtype: 'romance',
    timelineNote: null,
    createdAt: '2021-09-01',
    updatedAt: '2021-09-01'
  },
  {
    id: 'moment-people-7',
    userId: 'mock-user',
    limbId: 'people',
    branchId: 'branch-people-1',
    label: 'Got Engaged',
    description: 'On a walk in the Peaks. No grand gesture. Just right.',
    year: 2024,
    month: 8,
    mapPosition: 6,
    significance: 3,
    future: false,
    isTurningPoint: false,
    location: 'Peak District, UK',
    subtype: 'romance',
    timelineNote: null,
    createdAt: '2024-08-01',
    updatedAt: '2024-08-01'
  },

  // ── MONEY & FINANCE ────────────────────
  // 7 moments — debt, growth, risk
  {
    id: 'moment-finance-1',
    userId: 'mock-user',
    limbId: 'finance',
    branchId: 'branch-finance-1',
    label: '£28k Student Debt',
    description: 'Graduated with debt and no real plan to pay it off.',
    year: 2013,
    month: 7,
    mapPosition: 0,
    significance: 2,
    future: false,
    isTurningPoint: false,
    location: 'Manchester, UK',
    timelineNote: null,
    createdAt: '2013-07-01',
    updatedAt: '2013-07-01'
  },
  {
    id: 'moment-finance-2',
    userId: 'mock-user',
    limbId: 'finance',
    branchId: 'branch-finance-1',
    label: 'First Real Salary',
    description: '£32k in London. Felt rich. Was not rich.',
    year: 2015,
    month: 3,
    mapPosition: 1,
    significance: 2,
    future: false,
    isTurningPoint: false,
    location: 'London, UK',
    timelineNote: null,
    createdAt: '2015-03-01',
    updatedAt: '2015-03-01'
  },
  {
    id: 'moment-finance-3',
    userId: 'mock-user',
    limbId: 'finance',
    branchId: 'branch-finance-1',
    label: 'Paid Off Student Debt',
    description: 'Five years of chipping away. Done.',
    year: 2018,
    month: 11,
    mapPosition: 2,
    significance: 3,
    future: false,
    isTurningPoint: false,
    location: null,
    timelineNote: 'The first time money felt like it was working for me.',
    createdAt: '2018-11-01',
    updatedAt: '2018-11-01'
  },
  {
    id: 'moment-finance-4',
    userId: 'mock-user',
    limbId: 'finance',
    branchId: 'branch-finance-1',
    label: 'Started Investing',
    description: 'Index funds. Not exciting. Very effective.',
    year: 2019,
    month: 6,
    mapPosition: 3,
    significance: 2,
    future: false,
    isTurningPoint: false,
    location: null,
    timelineNote: null,
    createdAt: '2019-06-01',
    updatedAt: '2019-06-01'
  },
  {
    id: 'moment-finance-5',
    userId: 'mock-user',
    limbId: 'finance',
    branchId: 'branch-finance-1',
    label: 'Bought First Flat',
    description: 'East London. Tiny. Ours.',
    year: 2022,
    month: 6,
    mapPosition: 4,
    significance: 3,
    future: false,
    isTurningPoint: false,
    location: 'London, UK',
    timelineNote: null,
    createdAt: '2022-06-01',
    updatedAt: '2022-06-01'
  },
  {
    id: 'moment-finance-6',
    userId: 'mock-user',
    limbId: 'finance',
    branchId: 'branch-finance-1',
    label: 'Quit Salary for Startup',
    description: 'Gave up £95k to build something with no revenue.',
    year: 2024,
    month: 1,
    mapPosition: 5,
    significance: 3,
    future: false,
    isTurningPoint: false,
    location: null,
    timelineNote: 'The most financially terrifying and personally liberating thing I have done.',
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01'
  },
  {
    id: 'moment-finance-7',
    userId: 'mock-user',
    limbId: 'finance',
    branchId: 'branch-finance-1',
    label: 'Startup Profitable',
    description: 'The month we stop burning savings.',
    year: 2026,
    month: 9,
    mapPosition: 6,
    significance: 3,
    future: true,
    isTurningPoint: false,
    location: null,
    timelineNote: null,
    createdAt: '2025-01-01',
    updatedAt: '2025-01-01'
  },

  // ── WHO I'M BECOMING ───────────────────
  // 6 moments — identity shifts
  {
    id: 'moment-becoming-1',
    userId: 'mock-user',
    limbId: 'becoming',
    branchId: 'branch-becoming-1',
    label: 'Stopped Drinking',
    description: 'Not dramatic. Just noticed it was costing more than it gave.',
    year: 2017,
    month: 1,
    mapPosition: 0,
    significance: 2,
    future: false,
    isTurningPoint: false,
    location: null,
    timelineNote: null,
    createdAt: '2017-01-01',
    updatedAt: '2017-01-01'
  },
  {
    id: 'moment-becoming-2',
    userId: 'mock-user',
    limbId: 'becoming',
    branchId: 'branch-becoming-1',
    label: 'Therapy Changed Me',
    description: 'Two years of weekly sessions. Understood patterns I had been repeating for a decade.',
    year: 2019,
    month: 6,
    mapPosition: 1,
    significance: 3,
    future: false,
    isTurningPoint: false,
    location: 'Berlin, Germany',
    timelineNote: 'Best money I have ever spent.',
    createdAt: '2019-06-01',
    updatedAt: '2019-06-01'
  },
  {
    id: 'moment-becoming-3',
    userId: 'mock-user',
    limbId: 'becoming',
    branchId: 'branch-becoming-1',
    label: 'Stopped Needing Approval',
    description: 'Hard to say when exactly. But at some point other peoples opinions just got quieter.',
    year: 2021,
    month: null,
    mapPosition: 2,
    significance: 3,
    future: false,
    isTurningPoint: false,
    location: null,
    timelineNote: null,
    createdAt: '2021-06-01',
    updatedAt: '2021-06-01'
  },
  {
    id: 'moment-becoming-4',
    userId: 'mock-user',
    limbId: 'becoming',
    branchId: 'branch-becoming-1',
    label: 'Became a Builder',
    description: 'Identity shifted from someone who works to someone who creates.',
    year: 2023,
    month: null,
    mapPosition: 3,
    significance: 3,
    future: false,
    isTurningPoint: false,
    location: null,
    timelineNote: 'This is the most important shift so far.',
    createdAt: '2023-06-01',
    updatedAt: '2023-06-01'
  },
  {
    id: 'moment-becoming-5',
    userId: 'mock-user',
    limbId: 'becoming',
    branchId: 'branch-becoming-1',
    label: 'Learning to Rest',
    description: 'Realised productivity guilt was eating me. Still working on this one.',
    year: 2024,
    month: 9,
    mapPosition: 4,
    significance: 2,
    future: false,
    isTurningPoint: false,
    location: null,
    timelineNote: null,
    createdAt: '2024-09-01',
    updatedAt: '2024-09-01'
  },
  {
    id: 'moment-becoming-6',
    userId: 'mock-user',
    limbId: 'becoming',
    branchId: 'branch-becoming-1',
    label: 'Fully Present',
    description: 'The version of myself that is not always half somewhere else.',
    year: 2027,
    month: null,
    mapPosition: 5,
    significance: 3,
    future: true,
    isTurningPoint: false,
    location: null,
    timelineNote: null,
    createdAt: '2025-01-01',
    updatedAt: '2025-01-01'
  },
]

export const MOCK_DATA = {
  branches: MOCK_BRANCHES,
  moments: MOCK_MOMENTS,
}

// Summary for reference:
// Work:      8 moments (2013-2026)
// Health:    7 moments (2016-2026)
// People:    7 moments (2015-2024)
// Finance:   7 moments (2013-2026)
// Becoming:  6 moments (2017-2027)
// Total:    35 moments across 5 limbs
