// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

config({ path: ".env.local", override: true });

// `prisma generate` is pure codegen and needs no database connection, so a
// fresh clone (postinstall, typecheck, unit tests) must not require env setup.
// Commands that actually touch the datasource still fail fast without a URL.
const CODEGEN_COMMANDS = new Set(["generate"]);
const command = process.argv.find((arg) => !arg.startsWith("-") && CODEGEN_COMMANDS.has(arg));

const databaseUrl = process.env["DATABASE_URL"];
if (!databaseUrl && !command) {
  throw new Error("DATABASE_URL is required for Prisma.");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl ?? "postgresql://placeholder:placeholder@localhost:5432/placeholder",
  },
});
