import type { PursuitSpec } from "./seed-ai-qa-data";

/**
 * Alex QA map — honest descriptions (empty or short user-typed lines only).
 * 17 pursuits across 5 active themes; pleasures deliberately empty.
 */
export const ALEX_HONEST_PURSUITS = [
  // Self & Mind (becoming)
  {
    title: "Daily meditation",
    themeId: "becoming",
    categoryLabel: "Mind & wellbeing",
    status: "ACTIVE",
    significance: 5,
    description: "Doing 10 min mornings, aiming for 30",
    deadlineOn: "2026-12-31",
    mapGridQ: 1,
    mapGridR: 0,
    milestones: [
      { title: "7-day streak", completed: true, completedOn: "2026-05-15" },
      { title: "30-day streak", completed: true, completedOn: "2026-06-10" },
      { title: "60-day streak", completed: false },
    ],
  },
  {
    title: "Read more fiction",
    themeId: "pleasures",
    categoryLabel: "Books, film & culture",
    status: "PAUSED",
    significance: 2,
    description: "",
    deadlineOn: "2027-03-01",
    mapGridQ: -1,
    mapGridR: 1,
  },
  {
    title: "Digital sabbath",
    themeId: "becoming",
    categoryLabel: "Mind & wellbeing",
    status: "MAINTAINING",
    significance: 3,
    description: "",
    mapGridQ: 0,
    mapGridR: 1,
  },
  // Work & Career
  {
    title: "CeMAP qualification",
    themeId: "work",
    categoryLabel: "Qualifications",
    status: "ACTIVE",
    significance: 5,
    description: "Need all 3 modules to practise as mortgage advisor",
    deadlineOn: "2026-07-15",
    mapGridQ: 1,
    mapGridR: 0,
    milestones: [
      { title: "Module 1 passed", completed: true, completedOn: "2026-04-20" },
      { title: "Module 2 passed", completed: true, completedOn: "2026-06-01" },
      { title: "Module 3 exam", completed: false },
    ],
  },
  {
    title: "Lead product launch",
    themeId: "work",
    categoryLabel: "Jobs & roles",
    status: "ACTIVE",
    significance: 4,
    description: "",
    deadlineOn: "2026-09-30",
    mapGridQ: 2,
    mapGridR: 0,
    milestones: [
      { title: "Beta shipped", completed: true, completedOn: "2026-05-01" },
      { title: "Board review", completed: false },
      { title: "GA release", completed: false },
    ],
  },
  {
    title: "Public speaking",
    themeId: "work",
    categoryLabel: "Education & courses",
    status: "ACTIVE",
    significance: 3,
    description: "",
    deadlineOn: "2027-01-15",
    mapGridQ: -1,
    mapGridR: 0,
    milestones: [
      { title: "Joined Toastmasters", completed: true, completedOn: "2026-05-20" },
      { title: "First speech", completed: false },
    ],
  },
  {
    title: "Ask for promotion",
    themeId: "work",
    categoryLabel: "Jobs & roles",
    status: "PAUSED",
    significance: 4,
    description: "",
    deadlineOn: "2026-12-31",
    mapGridQ: 0,
    mapGridR: 1,
  },
  // Money & Finance
  {
    title: "£500,000 ISA",
    themeId: "finance",
    categoryLabel: "Assets & investing",
    status: "ACTIVE",
    significance: 4,
    description: "",
    deadlineOn: "2028-12-01",
    currentAmount: 125_000,
    targetAmount: 500_000,
    unit: "GBP",
    mapGridQ: 1,
    mapGridR: 0,
  },
  {
    title: "Clear credit card debt",
    themeId: "finance",
    categoryLabel: "Debts & obligations",
    status: "COMPLETE",
    significance: 3,
    description: "",
    deadlineOn: "2026-07-15",
    completedOn: "2026-06-15",
    mapGridQ: 2,
    mapGridR: 0,
  },
  {
    title: "Emergency fund",
    themeId: "finance",
    categoryLabel: "Safety net",
    status: "MAINTAINING",
    significance: 3,
    description: "",
    mapGridQ: -1,
    mapGridR: 1,
    milestones: [{ title: "£3,000 saved", completed: true, completedOn: "2026-03-10" }],
  },
  {
    title: "Rental income",
    themeId: "finance",
    categoryLabel: "Rental & property income",
    status: "MAINTAINING",
    significance: 4,
    description: "Tenant in place, rent £1,700/mo",
    currentAmount: 1700,
    unit: "GBP/month",
    mapGridQ: 0,
    mapGridR: 1,
  },
  // Health & Body
  {
    title: "Half-marathon",
    themeId: "health",
    categoryLabel: "Movement",
    status: "ACTIVE",
    significance: 4,
    description: "",
    deadlineOn: "2026-10-15",
    mapGridQ: 1,
    mapGridR: 0,
    milestones: [
      { title: "5k without stopping", completed: true, completedOn: "2026-04-01" },
      { title: "10k run", completed: false },
      { title: "Race registration", completed: false },
    ],
  },
  {
    title: "Meal prep Sundays",
    themeId: "health",
    categoryLabel: "Nutrition",
    status: "ACTIVE",
    significance: 2,
    description: "",
    deadlineOn: "2027-01-01",
    mapGridQ: -1,
    mapGridR: 0,
  },
  {
    title: "Invisalign",
    themeId: "health",
    categoryLabel: "Body & grooming",
    status: "ACTIVE",
    significance: 2,
    description: "",
    deadlineOn: "2026-11-30",
    mapGridQ: 0,
    mapGridR: 1,
  },
  // People & Relationships
  {
    title: "Plan wedding",
    themeId: "people",
    categoryLabel: "Family",
    status: "ACTIVE",
    significance: 5,
    description: "",
    deadlineOn: "2027-06-01",
    mapGridQ: 1,
    mapGridR: 0,
    milestones: [
      { title: "Venue booked", completed: true, completedOn: "2026-05-15" },
      { title: "Catering confirmed", completed: false },
      { title: "Invitations sent", completed: false },
    ],
  },
  {
    title: "Monthly family dinner",
    themeId: "people",
    categoryLabel: "Friendships",
    status: "MAINTAINING",
    significance: 3,
    description: "",
    mapGridQ: 0,
    mapGridR: 1,
  },
  {
    title: "Reconnect with uni friends",
    themeId: "people",
    categoryLabel: "Friendships",
    status: "ACTIVE",
    significance: 2,
    description: "",
    deadlineOn: "2026-12-31",
    mapGridQ: -1,
    mapGridR: 0,
  },
] satisfies PursuitSpec[];
