import type { EnrichAnswer } from "../src/lib/pursuit/pursuit-enrich-types";
import type { PursuitSpec, RelationshipSpec } from "./seed-ai-qa-data";

/** Alex Carter — 16 chapters, current taxonomy labels, mobile-native fields. */
export const ALEX_RICH_PURSUITS = [
  // Work & Career (5)
  {
    title: "CeMAP qualification",
    themeId: "work",
    categoryLabel: "Qualifications",
    status: "ACTIVE",
    significance: 5,
    background:
      "Studying through LIBF. Modules 1–2 passed; Module 3 exam in three weeks. Need this to advise on mortgages.",
    deadlineDaysFromNow: 18,
    mapGridQ: 1,
    mapGridR: 0,
    milestones: [
      { title: "Module 1 passed", completed: true, completedDaysAgo: 75 },
      { title: "Module 2 passed", completed: true, completedDaysAgo: 33 },
      { title: "Module 3 exam", completed: false },
    ],
    enrichAnswers: [
      {
        clarifierId: "cemap-route",
        prompt: "Which exam route are you on?",
        selectedOption: "London Institute of Banking & Finance",
        options: [
          "London Institute of Banking & Finance",
          "Self-study only",
          "Employer-sponsored",
          "Not decided yet",
        ],
      },
    ] satisfies EnrichAnswer[],
  },
  {
    title: "Lead product launch",
    themeId: "work",
    categoryLabel: "Projects & launches",
    status: "ACTIVE",
    significance: 4,
    background: "Compliance dashboard before September audit. Design signed off; build mid-sprint.",
    deadlineDaysFromNow: 45,
    timelineStartDaysAgo: 60,
    mapGridQ: 2,
    mapGridR: 0,
    milestones: [
      { title: "Beta shipped", completed: true, completedDaysAgo: 35 },
      { title: "Board review", completed: false },
      { title: "GA release", completed: false },
    ],
  },
  {
    title: "Public speaking",
    themeId: "work",
    categoryLabel: "Education & courses",
    status: "ACTIVE",
    significance: 3,
    deadlineDaysFromNow: 180,
    mapGridQ: -1,
    mapGridR: 0,
    milestones: [
      { title: "Joined Toastmasters", completed: true, completedDaysAgo: 45 },
      { title: "First speech", completed: false },
    ],
  },
  {
    title: "Senior Engineer at Acme",
    themeId: "work",
    categoryLabel: "Jobs & roles",
    status: "COMPLETE",
    significance: 4,
    background: "Handed over payments reliability work before moving toward advisory.",
    completedDaysAgo: 120,
    mapGridQ: 0,
    mapGridR: 1,
    milestones: [{ title: "Handover complete", completed: true, completedDaysAgo: 125 }],
  },
  {
    title: "Ask for promotion",
    themeId: "work",
    categoryLabel: "Jobs & roles",
    status: "PAUSED",
    significance: 4,
    deadlineDaysFromNow: 120,
    mapGridQ: -1,
    mapGridR: 1,
  },
  // Money & Finance (4)
  {
    title: "£500,000 ISA",
    themeId: "finance",
    categoryLabel: "Assets & investing",
    status: "ACTIVE",
    significance: 5,
    background: "Stocks and Shares ISA — contributing monthly after last year's raise.",
    deadlineDaysFromNow: 900,
    targetAmount: 500_000,
    currentAmount: 125_000,
    unit: "GBP",
    mapGridQ: 1,
    mapGridR: 0,
  },
  {
    title: "Clear credit card debt",
    themeId: "finance",
    categoryLabel: "Debts & loans",
    status: "COMPLETE",
    significance: 3,
    completedDaysAgo: 95,
    mapGridQ: 2,
    mapGridR: 0,
  },
  {
    title: "Emergency fund",
    themeId: "finance",
    categoryLabel: "Safety net & insurance",
    status: "MAINTAINING",
    significance: 3,
    mapGridQ: -1,
    mapGridR: 1,
    milestones: [{ title: "£3,000 saved", completed: true, completedDaysAgo: 110 }],
  },
  {
    title: "Rental income",
    themeId: "finance",
    categoryLabel: "Property income",
    status: "MAINTAINING",
    significance: 4,
    background: "Tenant in place — rent £1,700/mo.",
    currentAmount: 1700,
    unit: "GBP/month",
    amountBasis: "gross",
    mapGridQ: 0,
    mapGridR: 1,
  },
  // People & Relationships (2)
  {
    title: "Plan wedding",
    themeId: "people",
    categoryLabel: "Family",
    status: "ACTIVE",
    significance: 5,
    background: "Venue booked. Caterer and guest list by autumn — small London or Kent.",
    deadlineDaysFromNow: 120,
    mapGridQ: 1,
    mapGridR: 0,
    milestones: [
      { title: "Venue booked", completed: true, completedDaysAgo: 20 },
      { title: "Catering confirmed", completed: false },
      { title: "Invitations sent", completed: false },
    ],
    enrichAnswers: [
      {
        clarifierId: "wedding-size",
        prompt: "What size wedding are you aiming for?",
        selectedOption: "Small — under 50 guests",
        options: [
          "Small — under 50 guests",
          "Medium — 50–100",
          "Large — 100+",
          "Not sure yet",
        ],
      },
    ] satisfies EnrichAnswer[],
  },
  {
    title: "Monthly family dinner",
    themeId: "people",
    categoryLabel: "Friends & community",
    status: "MAINTAINING",
    significance: 3,
    mapGridQ: 0,
    mapGridR: 1,
  },
  // Self & Mind (2)
  {
    title: "Daily meditation",
    themeId: "becoming",
    categoryLabel: "Mind & wellbeing",
    status: "ACTIVE",
    significance: 5,
    background: "Ten minutes most mornings — aiming for thirty.",
    deadlineDaysFromNow: 180,
    mapGridQ: 1,
    mapGridR: 0,
    milestones: [
      { title: "7-day streak", completed: true, completedDaysAgo: 50 },
      { title: "30-day streak", completed: true, completedDaysAgo: 24 },
      { title: "60-day streak", completed: false },
    ],
  },
  {
    title: "Digital sabbath",
    themeId: "becoming",
    categoryLabel: "Mind & wellbeing",
    status: "MAINTAINING",
    significance: 3,
    mapGridQ: -1,
    mapGridR: 1,
  },
  // Health & Body (2)
  {
    title: "Half-marathon",
    themeId: "health",
    categoryLabel: "Training & sport",
    status: "ACTIVE",
    significance: 4,
    deadlineDaysFromNow: 100,
    mapGridQ: 1,
    mapGridR: 0,
    milestones: [
      { title: "5k without stopping", completed: true, completedDaysAgo: 94 },
      { title: "10k run", completed: false },
      { title: "Race registration", completed: false },
    ],
  },
  {
    title: "Meal prep Sundays",
    themeId: "health",
    categoryLabel: "Food & nutrition",
    status: "ACTIVE",
    significance: 2,
    deadlineDaysFromNow: 180,
    mapGridQ: -1,
    mapGridR: 0,
  },
  // Becoming — light active chapter (16th)
  {
    title: "Evening journaling",
    themeId: "becoming",
    categoryLabel: "Values & direction",
    status: "ACTIVE",
    significance: 2,
    background: "Ten minutes before bed — mood and what moved the day.",
    deadlineDaysFromNow: 200,
    mapGridQ: 0,
    mapGridR: 2,
  },
] satisfies PursuitSpec[];

/** Sparse control — one thin chapter, no cross-links. */
export const SAM_SPARSE_PURSUITS = [
  {
    title: "CeMAP qualification",
    themeId: "work",
    categoryLabel: "Qualifications",
    status: "ACTIVE",
    significance: 3,
    background: "Early research phase only.",
    deadlineDaysFromNow: 90,
    mapGridQ: 1,
    mapGridR: 0,
  },
] satisfies PursuitSpec[];

export const ALEX_ORIENTATION = "Keep growing, Build together";

export const ALEX_RELATIONSHIPS: RelationshipSpec[] = [
  { titleA: "CeMAP qualification", titleB: "Plan wedding", label: "Competing autumn priorities" },
  { titleA: "£500,000 ISA", titleB: "Plan wedding", label: "Savings vs wedding spend" },
  { titleA: "Half-marathon", titleB: "Daily meditation", label: "Wellbeing habits" },
];
