/** Shared quick-question prompt rules for reflect + pursuit enrich. */

export const CLARIFIER_MILESTONE_GROUNDING = [
  "MILESTONE GROUNDING (mandatory — read pursuit milestones in map context first):",
  "- Never ask a question whose answer is already established by a completed milestone (`completed: true`) or a structured field (`currentAmount`, `targetAmount`).",
  "- Never offer an answer option that contradicts a completed milestone.",
  '- Wrong: milestone "5k without stopping" is complete, but options include "Under 5k" for a running-distance question.',
  '- Right: ask about the next frontier — e.g. "Where are you on the jump to 10k?" with options like "Still building toward 10k" / "10k done, half-marathon next" / "Not sure yet".',
  "- Prefer questions about what is NOT yet captured — the next unknown, not what the map already proves.",
  "- If every plausible question is already answered by milestones or structured fields, return no clarifier.",
].join("\n");

export const CONTEXTUAL_QUICK_QUESTIONS = [
  "CONTEXTUAL QUICK QUESTIONS:",
  "When generating clarifiers for a pursuit, ask about the domain-specific detail that would MOST change how this pursuit should be understood. Use your world knowledge of the pursuit's domain.",
  "",
  CLARIFIER_MILESTONE_GROUNDING,
  "",
  "Examples of GOOD contextual questions (the kind to generate):",
  "",
  'For a debt pursuit ("Clear £10,000 credit card debt"):',
  '- "Is this on a 0% promotional rate, or are you paying interest?" → the answer changes urgency completely',
  '- "What\'s the monthly payment?" → grounds the timeline',
  "",
  'For a qualification ("CeMAP qualification"):',
  '- "Are you self-studying or enrolled in a course?" → changes the pace expectation',
  '- "Is this required for your current role or a career change?" → changes the significance framing',
  "",
  'For a fitness goal ("Half-marathon") when NO completed milestones yet:',
  '- "What\'s your current longest run?" → grounds where they actually are',
  '- "Is this a specific race with a registration date?" → deadline becomes real vs aspirational',
  "",
  'For a fitness goal ("Half-marathon") when "5k without stopping" is ALREADY complete:',
  '- Wrong: "What\'s your current longest run?" with "Under 5k" — the map already proves 5k.',
  '- Right: "Where are you on the jump to 10k?" with options reflecting progress beyond 5k.',
  "",
  'For a financial goal ("£500,000 ISA"):',
  '- "Is this a stocks-and-shares ISA or cash?" → changes the growth framing entirely',
  '- "What\'s your monthly contribution?" → makes progress concrete',
  "",
  'For a life event ("Plan wedding"):',
  '- "Do you have a venue booked?" → distinguishes dream from plan',
  '- "What\'s the budget range?" → grounds the financial implications',
  "",
  "RULES for contextual questions:",
  "- Ask ONE question per sync (max), about the detail that would most change the Reading",
  "- The question must have a CONCRETE answer (a fact, a number, a yes/no) — not an open reflection (\"How do you feel about this?\")",
  "- The answer options should be specific and plausible (not generic \"Yes / No / Not sure\")",
  "- Use world knowledge to ask what a domain expert would ask — the model KNOWS what matters for credit cards, mortgages, races, qualifications",
  "- Once the pursuit has rich context (description + answers ≥ 120 chars), stop asking — don't over-probe",
  "- NEVER ask about relationships between pursuits (see RELATIONSHIP QUESTIONS rule)",
  '- NEVER ask the user to evaluate their own motivation or commitment ("How important is this to you?") — significance already covers that',
  "",
  "Title-disambiguation questions are still allowed when the title is genuinely ambiguous — domain questions are ADDITIONAL, not a replacement.",
  "",
  "OPTIONS FORMAT:",
  "- 3-4 specific, plausible answer options — not generic",
  '- Wrong options: "Yes / No / Not sure / Other"',
  '- Right options for "Is this on a 0% rate?": "Yes, 0% until [month]" / "No, standard interest rate" / "Not sure — need to check"',
  "- Options must be consistent with completed milestones — never include bands the map already disproves",
  "- The options should cover the realistic range for this domain",
].join("\n");

export const CREATE_CLARIFIER_MILESTONE_GROUNDING = [
  "MILESTONE GROUNDING:",
  "- If completed milestones are provided in context, never ask what they already prove and never offer contradicting options.",
  '- Wrong: "5k without stopping" complete but options include "Under 5k".',
  "- Prefer the next frontier the map does not yet capture.",
  "- If the title implies prior progress (e.g. returning to a goal), do not ask beginner baseline questions — ask what changed or what is next.",
].join("\n");
